### ISSUE TITLE
The image element contains cross-origin data, and may not be loaded

### ISSUE THREAD

**Issue by daveisagit** [Cortado-J/Minky#1]
Seems there's some CORS issue on my clone. 

```
gpu-browser.min.js:14 Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.
    at WebGL2KernelValueHTMLImage.updateValue (file:///C:/Users/david.budd/Documents/GitHub/Minky/dist/gpu-browser.min.js:14:272971)
    at WebGL2Kernel.run (file:///C:/Users/david.budd/Documents/GitHub/Minky/dist/gpu-browser.min.js:14:301785)
    at WebGL2Kernel.t (file:///C:/Users/david.budd/Documents/GitHub/Minky/dist/gpu-browser.min.js:14:379491)
    at WebGL2Kernel.t (file:///C:/Users/david.budd/Documents/GitHub/Minky/dist/gpu-browser.min.js:14:379725)
    at n (file:///C:/Users/david.budd/Documents/GitHub/Minky/dist/gpu-browser.min.js:14:379773)
    at doMinkowski (file:///C:/Users/david.budd/Documents/GitHub/Minky/index.html:127:7)
    at HTMLImageElement.onload (file:///C:/Users/david.budd/Documents/GitHub/Minky/index.html:134:9)
```

I take it you don't get it (maybe you have a browser setting to allow it?)
![image](https://user-images.githubusercontent.com/724703/118374340-71537380-b5b3-11eb-92b2-84f0baaa26b1.png)
This may be relevant
https://webglfundamentals.org/webgl/lessons/webgl-cors-permission.html

**Comment by Cortado-J** [comment]
I had this problem too and fixed it by changing a setting in Chrome.
Can't find it now!

**Comment by Cortado-J** [comment]
Weird - I found the setting in Chrome pretty easily before - can't seem to find it now.
Can't see at the moment how to fix this - do you understand this CORS thing sufficiently to see how it could be fixed?

**Comment by Cortado-J** [comment]
I'm guessing leaving my browser to allow cross-origin data isn;t recommended.
For some reason not can;t fnd the setting  :-(

**Comment by Cortado-J** [comment]
I realised what I did.
I ran chrome from terminal (on Mac) using option --allow-file-access-from-files
So used:
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --allow-file-access-from-files
But this clearly isn't a long-term solution and I need to fix this in the source.
 I'll research further but you could try this option if you're ok with the security!

**Comment by Cortado-J** [comment]
Hi Dave,
From what I can see, it might be easier to just run Minky "in a small web server".
Do you think that sounds like the best way to deal with this CORS issue?
If so, does that then mean that we each need to set up "a small web server" on our machines to do testing.
All seems a bit convoluted !!

**Comment by Cortado-J** [comment]
I've tried in the code uncommented the crossOrigin line:
```
    function loadImage(imageName) {
      const image = document.createElement('img')
      //image.crossOrigin = ""
      image.src = 'images/' + imageName + '.png'
      return image
    }
```
And tried crossOrigin='anonymous'
But no cigar!

**Comment by daveisagit** [comment]
Ultimately the image files being referenced will be referenced in the HTML as a url to probably the same webserver as would any uploaded ones. So yes I'll just configure my dev IDE (using VS code) to start up a local web server.

**Comment by Cortado-J** [comment]
Glad you worked out a way forward. I've found a way for Atom (The editor I'm using) to run up a local server which refreshes whenever there is a change. 😎
